require('dotenv').config();
const express = require('express');
const cors = require('cors');
const app = express();
const seed = require('./seeders/seed');
const authRoutes = require('./routes/auth');
const reviewRoutes = require('./routes/reviews');
const reviewCycleRoutes = require('./routes/reviewCycles');
app.use(cors());
app.use(express.json());
app.use('/api/auth', authRoutes);
app.use('/api/reviews', reviewRoutes);
app.use('/api/review-cycles', reviewCycleRoutes);
seed();
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));