const express = require('express');
const router = express.Router();
const applicationController = require('../controllers/applicationController');
const { authenticate } = require('../middleware/auth');
router.use(authenticate);
router.post('/', applicationController.create);
router.get('/', applicationController.getAll);
router.put('/:id', applicationController.update);
router.delete('/:id', applicationController.delete);
module.exports = router;