const express = require('express');
const router = express.Router();
const { authenticate } = require('../middleware/auth');
const { create, getAll, update, remove } = require('../controllers/prompts');
router.use(authenticate);
router.post('/', create);
router.get('/', getAll);
router.put('/:id', update);
router.delete('/:id', remove);
module.exports = router;